# -*- coding: utf-8 -*-
"""nethwin python assgn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u55WyrRmfXjcXp571dkrk6_dvDfDfkEz
"""

print("attendance checker")
print()

name=input("enter student name:")

total_classes=int(input("enter total classes held:"))
attended_classes=int(input("enter total classes attended:"))

percentage=(total_classes/attended_classes)*100
print()

print("student name:",name)
print("attendance percentage:",percentage)

if percentage>=75:
 print("allowed for exam")
else:
 print("not allowed for exam")